// Auto-generated by vite.config.mts
export const eaogModules = {
  'Vibe Dev/vibe-dev.eaog.js': () => import('/Users/wangqing/IdeaProjects/abc-study-copilot/packages/aia-se-comp/design/Vibe Dev/vibe-dev.eaog.js'),
  '完善项目注释/完善项目注释.eaog.js': () => import('/Users/wangqing/IdeaProjects/abc-study-copilot/packages/aia-se-comp/design/完善项目注释/完善项目注释.eaog.js'),
  '生成项目知识库/控制【框架】.eaog.js': () => import('/Users/wangqing/IdeaProjects/abc-study-copilot/packages/aia-se-comp/design/生成项目知识库/控制【框架】.eaog.js'),
  '生成项目知识库/生成项目知识库.eaog.js': () => import('/Users/wangqing/IdeaProjects/abc-study-copilot/packages/aia-se-comp/design/生成项目知识库/生成项目知识库.eaog.js')
};
