import {defineConfig} from '@vben/vite-config';
import {loadEnv} from 'vite';
import {fileURLToPath} from 'url';
import {dirname, resolve, join} from 'path';

import fs from 'fs';
import fg from 'fast-glob';
import chokidar from 'chokidar';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default defineConfig(async ({mode}) => {
  const env = loadEnv(mode, process.cwd());
  const eaogsDir = env.VITE_EAOGS_PATH;
  if (!eaogsDir) throw new Error('VITE_EAOGS_PATH is not set');
  const outputFile = resolve(__dirname, 'src/eaog-modules.ts');

  return {
    application: {},
    vite: {
      plugins: [
        // 生成eaog模块映射 注意： 弃用，改用 symbol link eaoDir到aia-svc/public/cp-store 的方法
        // eaogPlugin(eaogsDir, outputFile),
      ],
      server: {
        proxy: {
          '/api': {
            changeOrigin: true,
            rewrite: (path) => path.replace(/^\/api/, ''),
            // mock代理目标地址
            target: 'http://localhost:5320/api',
            ws: true,
          },
        },
      },
    },
  };
});


function generateEaogModuleMap(eaogsDir: string, outFile: string) {
  const files = fg.sync('**/*.cp.js', {cwd: eaogsDir, onlyFiles: true});

  const lines = files.map(file => {
    const absPath = join(eaogsDir, file).replace(/\\/g, '/');
    return `  '${file}': () => import('${absPath}')`;
  });

  const output = `// Auto-generated by vite.config.mts\n//@ts-nocheck\nexport const eaogModules = {\n${lines.join(',\n')}\n};\n`;
    fs.writeFileSync(outFile, output, 'utf-8');
  }

function eaogPlugin(eaogsDir: string, outFile: string): import('vite').Plugin {
  return {
    name: 'vite-plugin-eaog-modules',

    buildStart() {
      generateEaogModuleMap(eaogsDir, outFile);
    },

    configureServer(server) {
      console.log('[eaog-plugin] watching:', eaogsDir);

      const watcher = chokidar.watch(eaogsDir, {
        ignored: (watchPath, stats) => {
          // 仅保留 .eaog.js 文件
          return stats?.isFile() && !watchPath.endsWith('.cp.js');
        },
        ignoreInitial: true,
      });

      const reload = () => {
        console.log('[eaog-plugin] files changed, regenerating...');
        generateEaogModuleMap(eaogsDir, outFile);
        server.ws.send({ type: 'full-reload' });
      };

      watcher
        .on('all', (event, path) => {
          console.log(`[eaog-plugin] ${event} detected on ${path}`);
        })
        .on('add', reload)
        .on('unlink', reload)
        .on('change', reload);
    }
  };
}


