import { defineConfig } from '@vben/vite-config';
import { loadEnv } from 'vite';
import { fileURLToPath } from 'url';
import { dirname, resolve, join } from 'path';

import fs from 'fs';
import fg from 'fast-glob';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export default defineConfig(async ({ mode }) => {
  const env = loadEnv(mode, process.cwd());
  const eaogsDir = env.VITE_EAOGS_PATH;
  if (!eaogsDir) throw new Error('VITE_EAOGS_PATH is not set');

  const outputFile = resolve(__dirname, 'src/eaog-modules.ts');
  generateEaogModuleMap(eaogsDir, outputFile);

  return {
    application: {},
    vite: {
      alias: {
        '@eaogs': resolve(__dirname, eaogsDir),
      },
      server: {
        proxy: {
          '/api': {
            changeOrigin: true,
            rewrite: (path) => path.replace(/^\/api/, ''),
            // mock代理目标地址
            target: 'http://localhost:5320/api',
            ws: true,
          },
        },
      },
    },
  };
});


function generateEaogModuleMap(eaogsDir: string, outFile: string) {
  const files = fg.sync('**/*.eaog.js', { cwd: eaogsDir, onlyFiles: true });

  const lines = files.map(file => {
    const absPath = join(eaogsDir, file).replace(/\\/g, '/');
    return `  '${file}': () => import('${absPath}')`;
  });

  const output = `// Auto-generated by vite.config.mts\nexport const eaogModules = {\n${lines.join(',\n')}\n};\n`;
  fs.writeFileSync(outFile, output, 'utf-8');
}

